Repository Spice08/Dice-Simulator, pull requests merged in 2022-10, with the labels that each got.

#1 Add Output File
  Output.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#2 Add readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#4 Added Image of Dice and Description into Text File
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#5 Add GUI version of dice simulator
  GUIDiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#6 GUI FIle Error Resolved
  GUIDiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#7 Uploading ScreenShot For GUI Version
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#8 Added module not found solution
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#9 Info about Tkinter
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#10 Added Project File Struct
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#11 Added actual code that works
  DiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#12 fixed a possible logical error
  DiceSimulator.py
  GUIDiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 improved DiceSimulator.py
  DiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Update DiceSimulator.py
  DiceSimulator.py
Labels: hacktoberfest, hacktoberfest-accepted
